// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqLEEleep0nrHc2UXSSr5fv7zJwmNbJjk',
    appId: '1:47644387836:web:98b9e81789e092a5e9aa79',
    messagingSenderId: '47644387836',
    projectId: 'event-reservation-app-34d5b',
    authDomain: 'event-reservation-app-34d5b.firebaseapp.com',
    storageBucket: 'event-reservation-app-34d5b.firebasestorage.app',
    measurementId: 'G-KW7JFWQ3RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLjQEUgNLNEcCm9Q0Vk1Vfeqdg_CuJOM',
    appId: '1:47644387836:android:73a30fb35d5fcbdbe9aa79',
    messagingSenderId: '47644387836',
    projectId: 'event-reservation-app-34d5b',
    storageBucket: 'event-reservation-app-34d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWNTdMnM-K6rrEw5f2fP8urAkPDgUdXo4',
    appId: '1:47644387836:ios:d3ed1472769cf13ae9aa79',
    messagingSenderId: '47644387836',
    projectId: 'event-reservation-app-34d5b',
    storageBucket: 'event-reservation-app-34d5b.firebasestorage.app',
    iosBundleId: 'com.example.eventReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWNTdMnM-K6rrEw5f2fP8urAkPDgUdXo4',
    appId: '1:47644387836:ios:d3ed1472769cf13ae9aa79',
    messagingSenderId: '47644387836',
    projectId: 'event-reservation-app-34d5b',
    storageBucket: 'event-reservation-app-34d5b.firebasestorage.app',
    iosBundleId: 'com.example.eventReservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqLEEleep0nrHc2UXSSr5fv7zJwmNbJjk',
    appId: '1:47644387836:web:b3e6697a46398164e9aa79',
    messagingSenderId: '47644387836',
    projectId: 'event-reservation-app-34d5b',
    authDomain: 'event-reservation-app-34d5b.firebaseapp.com',
    storageBucket: 'event-reservation-app-34d5b.firebasestorage.app',
    measurementId: 'G-TC4Z1MGMMR',
  );
}
